// Generated by CoffeeScript 1.3.1
(function() {
  var addCouple, addDance, addJudge, couples, dances, generateMarks, judges, removeCouple, removeDance, removeJudge;

  couples = [];

  judges = [];

  dances = [];

  $(function() {
    $('h1').click(function() {
      return $(this).hide('slow');
    });
    $('#coupleAdd').click(function() {
      return addCouple();
    });
    $('#coupleRemove').click(function() {
      return removeCouple();
    });
    $('#judgeAdd').click(function() {
      return addJudge();
    });
    $('#judgeRemove').click(function() {
      return removeJudge();
    });
    $('#danceAdd').click(function() {
      return addDance();
    });
    $('#danceRemove').click(function() {
      return removeDance();
    });
    return $('#marksGen').click(function() {
      return generateMarks();
    });
  });

  addCouple = function() {
    var newDivContent, thisIndex;
    newDivContent = '<div><input type="text" class="numberInput">';
    newDivContent += '<input type="text" class="nameInput">';
    newDivContent += '<br /></div>';
    $('#coupleFields').append(newDivContent);
    couples.push({
      number: "",
      name: ""
    });
    thisIndex = couples.length - 1;
    $('#coupleFields .numberInput').last().focusout(function() {
      return couples[thisIndex].number = this.value;
    });
    return $('#coupleFields .nameInput').last().focusout(function() {
      return couples[thisIndex].name = this.value;
    });
  };

  removeCouple = function() {
    if (couples.length < 1) {
      return;
    }
    couples.pop();
    return $('#coupleFields div:last').remove();
  };

  addJudge = function() {
    var newDivContent, thisIndex;
    newDivContent = '<div><input type="text" class="numberInput">';
    newDivContent += '<input type="text" class="nameInput">';
    newDivContent += '<br /></div>';
    $('#judgeFields').append(newDivContent);
    judges.push({
      number: "",
      name: ""
    });
    thisIndex = judges.length - 1;
    $('#judgeFields .numberInput').last().focusout(function() {
      return judges[thisIndex].number = this.value;
    });
    return $('#judgeFields .nameInput').last().focusout(function() {
      return judges[thisIndex].name = this.value;
    });
  };

  removeJudge = function() {
    if (judges.length < 1) {
      return;
    }
    judges.pop();
    return $('#judgeFields div:last').remove();
  };

  addDance = function() {
    var newDivContent, thisIndex;
    newDivContent = '<div><input type="text" class="numberInput">';
    newDivContent += '<input type="text" class="nameInput">';
    newDivContent += '<br /></div>';
    $('#danceFields').append(newDivContent);
    dances.push({
      number: "",
      name: ""
    });
    thisIndex = dances.length - 1;
    $('#danceFields .numberInput').last().focusout(function() {
      return dances[thisIndex].number = this.value;
    });
    return $('#danceFields .nameInput').last().focusout(function() {
      return dances[thisIndex].name = this.value;
    });
  };

  removeDance = function() {
    if (dances.length < 1) {
      return;
    }
    dances.pop();
    return $('#danceFields div:last').remove();
  };

  generateMarks = function() {
    var couple, dance, judge, newTable, _i, _j, _k, _l, _len, _len1, _len2, _len3, _results;
    if (couples.length < 1 || judges.length < 1 || dances.length < 1) {
      return;
    }
    $('#marks').empty();
    _results = [];
    for (_i = 0, _len = dances.length; _i < _len; _i++) {
      dance = dances[_i];
      newTable = '<div><h3>' + dance.name + '</h3>';
      newTable += '<table><tr><th></th>';
      for (_j = 0, _len1 = judges.length; _j < _len1; _j++) {
        judge = judges[_j];
        newTable += '<th>' + judge.number + '</th>';
      }
      newTable += '</tr>';
      for (_k = 0, _len2 = couples.length; _k < _len2; _k++) {
        couple = couples[_k];
        newTable += '<tr><td>' + couple.number + '</td>';
        for (_l = 0, _len3 = judges.length; _l < _len3; _l++) {
          judge = judges[_l];
          newTable += '<td><input type="text"></td>';
        }
      }
      newTable += '<br /></div>';
      _results.push($('#marks').append(newTable));
    }
    return _results;
  };

}).call(this);
